alias chrome="/Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome"
alias vim="nvim"
alias cleantex="rm *.aux *.log *.out"
alias l="ls -al"
alias skim="open -a Skim"

alias tally="tmux new -c ~/Developer/tallybook"
alias dots="tmux new -c ~/dotfiles"
alias site="tmux new -c ~/Developer/personal-site"
alias math="tmux new -c ~/Documents/math566"
alias prog="tmux new -c ~/Documents/eecs490"
alias sys="tmux new -c ~/Developer/eecs491/mbickers.4"

# Setup prompt
autoload -Uz vcs_info
zstyle ':vcs_info:git:*' formats '(%b) '

setopt prompt_subst
precmd_functions+=("vcs_info &> /dev/null")
PROMPT="%3~ \${vcs_info_msg_0_}%# "

if [[ -n "$USE_VENV" ]]; then
    source "env/bin/activate";
fi

# opam configuration
[[ ! -r /Users/maxbickers/.opam/opam-init/init.zsh ]] || source /Users/maxbickers/.opam/opam-init/init.zsh  > /dev/null 2> /dev/null
