alias chrome="/Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome"
alias vim="nvim"
alias cleantex="rm *.aux *.log"
alias l="ls -al"

alias tally="tmux new -c ~/Developer/tallybook"
alias dots="tmux new -c ~/dotfiles"
alias math="tmux new -c ~/Developer/math565"
alias algo="tmux new -c ~/Developer/eecs477"
alias site="tmux new -c ~/Developer/personal-site"
alias web="tmux new -c ~/Developer/p3-insta485-clientside -e USE_VENV=1"

# Setup prompt
autoload -Uz vcs_info
zstyle ':vcs_info:git:*' formats '(%b) '

setopt prompt_subst
precmd_functions+=("vcs_info &> /dev/null")
PROMPT="%3~ \${vcs_info_msg_0_}%# "

if [[ -n "$USE_VENV" ]]; then
    source "env/bin/activate";
fi
